name: Deploy RMS Testing
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
 
            echo "🚀 Starting Deployment..."
 
            if [ ! -d "/var/www/testing-portal/.git" ]; then
              git clone https://github.com/penumetcha9/testing-portal.git /var/www/testing-portal
            fi
 
            cd /var/www/testing-portal
            git pull origin main
 
            cd backend
            npm install
            pm2 restart backend-app || pm2 start index.js --name backend-app
 
            cd ../frontend
            npm install
            npm run build
 
            sudo systemctl reload nginx
 
            echo "✅ Done"
