script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_deploy
            cd /var/www/rmstesting
            git fetch origin main
            git reset --hard origin/main
            cd frontend/application
            npm install
            npm run build
            pm2 restart rmstesting